document.addEventListener('DOMContentLoaded', () => {
        // 默认打开第一个选项卡
            document.querySelector('.tablinks.active').click();

                // 加载配置
                    fetch('/api/settings')
                            .then(response => response.json())
                                    .then(settings => {
                                                const list = document.getElementById('accelerators-list');
                                                            settings.accelerators.forEach(url => {
                                                                            addAcceleratorItem(url);
                                                                                        });
                                                                                                    updateDeleteButtons();
                                                                                                            });
                                                                                                            });

                                                                                                            function openTab(evt, tabName) {
                                                                                                                const tabcontent = document.getElementsByClassName('tabcontent');
                                                                                                                    const tablinks = document.getElementsByClassName('tablinks');

                                                                                                                        // 隐藏所有 tabcontent
                                                                                                                            for (let i = 0; i < tabcontent.length; i++) {
                                                                                                                                    tabcontent[i].classList.remove('active');
                                                                                                                                        }

                                                                                                                                            // 移除所有 tablinks 的 active 类
                                                                                                                                                for (let i = 0; i < tablinks.length; i++) {
                                                                                                                                                        tablinks[i].classList.remove('active');
                                                                                                                                                            }

                                                                                                                                                                // 显示当前 tab，并添加 active 类到当前按钮
                                                                                                                                                                    document.getElementById(tabName).classList.add('active');
                                                                                                                                                                        evt.currentTarget.classList.add('active');
                                                                                                                                                                        }

                                                                                                                                                                        function addAccelerator() {
                                                                                                                                                                            const url = document.getElementById('acceleratorUrl').value;
                                                                                                                                                                                if (url) {
                                                                                                                                                                                        addAcceleratorItem(url);
                                                                                                                                                                                                document.getElementById('acceleratorUrl').value = '';
                                                                                                                                                                                                        updateDeleteButtons();
                                                                                                                                                                                                            }
                                                                                                                                                                                                            }

                                                                                                                                                                                                            function addAcceleratorItem(url) {
                                                                                                                                                                                                                const list = document.getElementById('accelerators-list');
                                                                                                                                                                                                                    const li = document.createElement('li');
                                                                                                                                                                                                                        li.className = 'input-group';
                                                                                                                                                                                                                            const input = document.createElement('input');
                                                                                                                                                                                                                                input.type = 'text';
                                                                                                                                                                                                                                    input.value = url;
                                                                                                                                                                                                                                        input.readOnly = true;
                                                                                                                                                                                                                                            const deleteButton = document.createElement('button');
                                                                                                                                                                                                                                                deleteButton.textContent = '删除';
                                                                                                                                                                                                                                                    deleteButton.className = 'delete-button';
                                                                                                                                                                                                                                                        deleteButton.onclick = () => {
                                                                                                                                                                                                                                                                if (confirm(`请确认是否删除该地址: ${url}`)) {
                                                                                                                                                                                                                                                                            li.remove();
                                                                                                                                                                                                                                                                                        updateDeleteButtons();
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                    };
                                                                                                                                                                                                                                                                                                        li.appendChild(input);
                                                                                                                                                                                                                                                                                                            li.appendChild(deleteButton);
                                                                                                                                                                                                                                                                                                                list.appendChild(li);
                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                function updateDeleteButtons() {
                                                                                                                                                                                                                                                                                                                    const list = document.getElementById('accelerators-list');
                                                                                                                                                                                                                                                                                                                        const deleteButtons = list.querySelectorAll('button');
                                                                                                                                                                                                                                                                                                                            deleteButtons.forEach(button => {
                                                                                                                                                                                                                                                                                                                                    button.style.display = (list.children.length > 1) ? 'inline-block' : 'none';
                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                        function searchImages() {
                                                                                                                                                                                                                                                                                                                                            const query = document.getElementById('searchQuery').value;
                                                                                                                                                                                                                                                                                                                                                const results = document.getElementById('results');
                                                                                                                                                                                                                                                                                                                                                    results.innerHTML = ''; // 清空结果区域

                                                                                                                                                                                                                                                                                                                                                        fetch(`/api/search?query=${query}`)
                                                                                                                                                                                                                                                                                                                                                                .then(response => response.json())
                                                                                                                                                                                                                                                                                                                                                                        .then(data => displayRepositories(data));
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                        function displayRepositories(repositories) {
                                                                                                                                                                                                                                                                                                                                                                            const results = document.getElementById('results');
                                                                                                                                                                                                                                                                                                                                                                                results.innerHTML = ''; // 清空结果区域
                                                                                                                                                                                                                                                                                                                                                                                    repositories.forEach(repo => {
                                                                                                                                                                                                                                                                                                                                                                                            const repoItem = document.createElement('div');
                                                                                                                                                                                                                                                                                                                                                                                                    repoItem.className = 'repo-item';
                                                                                                                                                                                                                                                                                                                                                                                                            repoItem.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>${repo.name}</strong></p>
                                                                                                                                                                                                                                                                                                                                                                                                                                    <p>${repo.description}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>拉取次数: ${repo.pull_count} | 星标: ${repo.star_count}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p>最后更新时间: ${repo.last_updated}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            repoItem.onclick = () => displayRepositoryDetails(repo.name);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    results.appendChild(repoItem);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function displayRepositoryDetails(repoName) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            fetch(`/api/repository/${repoName}`)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    .then(response => response.json())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .then(tags => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        const details = document.getElementById('details');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    details.innerHTML = `
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h3>${repoName} 详情</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ${tags.map(tag => `<li>${tag} <button onclick="pullImage('${repoName}:${tag}')">拉取</button></li>`).join('')}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    `;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            function pullImage(imageName) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fetch(`/api/pull?image=${imageName}`, { method: 'POST' })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        .then(response => response.json())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .then(data => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (data.success) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            alert('镜像拉取成功');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert('镜像拉取失败');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            document.getElementById('settings-form').addEventListener('submit', function (event) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                event.preventDefault();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const accelerators = Array.from(document.getElementById('accelerators-list').children).map(li => li.querySelector('input').value);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        fetch('/api/settings', {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                method: 'POST',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        headers: {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    'Content-Type': 'application/json',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    body: JSON.stringify({ accelerators }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        })
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            .then(response => response.json())
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                .then(data => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (data.success) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    alert('设置已保存');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        alert('保存设置时出错');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    });
})